### ISSUE TITLE
E1696 cannot open source file "iostream"

### ISSUE THREAD

**Issue by deva22github** [deva22github/task1#1]
someone please help me with this issue.. Here is the simple code I did,

![Capture](https://user-images.githubusercontent.com/71824038/103475305-11adb600-4dd2-11eb-8057-d967324a9c0a.JPG)

**Comment by deva22github** [comment]
@StarGate-One.. could u please help?

**Comment by StarGate-One** [comment]
The editor you are using does not know where to find <iostream> library.
If using Visual Studio 2019, the libraries are installed automatically when the **Desktop development with C++** workload is installed.
If you are using another editor (as there are many) to write C++ code, it needs to be configured on where to find the libraries, my experience is with Visual Studio 2017 and 2019.
I do not use Visual Studio Code, gcc, mingw, msys2, cygwin, etc.

**Comment by deva22github** [comment]
I'm using Visual Studio 2019 with Desktop development with C++ only sir

**Comment by deva22github** [comment]
Yes, I'm using Visual Studio 2019 and Desktop development with c++ installed

**Comment by StarGate-One** [comment]
You might try to google or bing search for ideas/suggestions on what it could be?
You could try a repair installation of visual studio then, as iostream is part of visual studio.

**Comment by deva22github** [comment]
ok sure, thank u for looking at this sir
